FROM ghcr.io/glimmer-labs/wolfi-caddy:latest AS build

RUN dxcaddy github.com/lucaslorentz/caddy-docker-proxy/v2

FROM cgr.dev/chainguard/static:latest

ENV XDG_DATA_HOME=/data
ENV XDG_CONFIG_HOME=/config
ENV DEFAULT_PLUGINS=github.com/lucaslorentz/caddy-docker-proxy/v2

EXPOSE 80
EXPOSE 443
EXPOSE 443/udp
EXPOSE 2019

WORKDIR /app

COPY --link --from=build /usr/bin/caddy /usr/bin/caddy

#Required to bind to privileged ports and access Docker socket
USER root 

CMD ["caddy", "docker-proxy"]